### ISSUE TITLE
Read-only inputs are partially obstructed by padding in Firefox

### ISSUE THREAD

**Issue by mjbradford89** [natecavanaugh/lexicon#6]
Read-only inputs are partially obstructed by padding in Firefox.  This issue was found in liferay-portal master, https://issues.liferay.com/browse/LPS-57663.  And is reproducible at http://natecavanaugh.github.io/lexicon/content/form-elements/ as well.

![image](https://cloud.githubusercontent.com/assets/6517855/9313485/1599e1d4-44d8-11e5-8239-e1834c18f4b9.png)

![image](https://cloud.githubusercontent.com/assets/6517855/9313453/f196e4bc-44d7-11e5-8e5d-47e590f96894.png)

**Comment by natecavanaugh** [comment]
Heya Mike,
Thanks for reporting this. Patrick has fixed it now :)
