### ISSUE TITLE
Button group z-index causing issues in liferay-portal

### ISSUE THREAD

**Issue by mjbradford89** [natecavanaugh/lexicon#7]
There is a bug in portal where a button group is appearing in front of a autocomplete list.  https://issues.liferay.com/browse/LPS-58060

Seems to be caused by this z-index: https://github.com/natecavanaugh/lexicon/blob/master/src/scss/atlas-theme/_button-groups.scss#L24

**Comment by pat270** [comment]
Fixed by https://github.com/natecavanaugh/lexicon/commit/40c9932c832965726f05796347ed462222597e57
